[package]
name = "ch2_logic"
version = "0.1.0"
edition = "2024"
default-run = "step7_best"

[dependencies]
bevy = { workspace = true }
bevy_rand = { workspace = true }
rand = { workspace = true }
ch1_board = { path = "../ch1_board" }
